FROM apache/airflow:2.10.0-python3.11

USER root
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements-airflow.txt .
RUN pip install --no-cache-dir -r requirements-airflow.txt

COPY --chown=airflow:root . /opt/airflow/src/indialens
